import { useState } from "react";
import { DomainTab } from "./components/DomainTab";
import { TabNav } from "./components/TabNav";
import { VideoPanel } from "./components/VideoPanel";
import type { DomainKey } from "./types";

const DOMAINS: { key: DomainKey; label: string }[] = [
  { key: "stocks", label: "Stocks & Mutual Funds" },
  { key: "commodities", label: "Commodities" },
  { key: "ai", label: "AI" },
  { key: "semiconductors", label: "Semiconductors" },
];

export default function App() {
  const [active, setActive] = useState<DomainKey>("stocks");
  const [videoOpen, setVideoOpen] = useState(false);

  return (
    <div className="app">
      <header className="header">
        <div className="brand">
          <span className="logo">◈</span>
          <div>
            <h1>Market &amp; Tech Briefing</h1>
            <p className="subtitle">Daily AI-generated digest · refreshed 12:00 AM IST</p>
          </div>
        </div>
        <button className="video-btn" onClick={() => setVideoOpen(true)}>
          ▶ Daily Video
        </button>
      </header>

      <TabNav domains={DOMAINS} active={active} onSelect={setActive} />

      <main className="content">
        <DomainTab key={active} domain={active} />
      </main>

      {videoOpen && <VideoPanel onClose={() => setVideoOpen(false)} />}

      <footer className="footer">
        Sources aggregated from public RSS/news feeds · Insights generated by Claude
      </footer>
    </div>
  );
}
